### ISSUE TITLE
Forum: medium term todo list

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1677]
- [ ] ~Instructor/full access ta can specify a 'lock' date for a thread.  After that date, all can view, but only instructor can edit.~  

- [ ] ~~Original author can edit a post if a thread is not locked~~

- [ ] ~~Instructor/full access ta can view/undelete/unhide posts~~

- [x] allow students to 'pin' threads

- [x] thread categories, and viewing/sorting by categories

**Comment by andrewaikens87** [comment]
Hi @scopeInfinity , once you complete the current issue you are working on I think a good next issue could be student pinned threads. This is where a student can self pin a thread that will bump it up to the top of the thread list, below announcements. Students can use this to flag important threads that they are going to return to later. We will also need to have the ability to unpin the threads as well. We can discuss the design through slack.
