### ISSUE TITLE
Forum: short term todo list

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1678]
- [x] Instructor/full access ta can add announcement label to existing thread

- [x] Instructor/full access ta can edit a post  (includes adding image attachment)

- [x] allow reply to specific post in thread

- [x] allow html tags for fixed width font (but restrict most html/scripting!)

- [x] allow html for hyperlinks

- [ ] inline image attachemnts

- [x] multiple image attachements

- [x] instructor/full accees/ limited access posts should be visually different (different background)

- [x] Confirm all items from #1632 are in this issue or in issue #1677

- [x] Make showing anonymous / full user information more intuitive

**Comment by ndixita** [comment]
@bmcutler I would like to make a suggestion here. We could also have a feature to tag/label the posts so that students enrolled for the particular course can filter the discussions by course. Also, there can be a feature to subscribe to various tags so that students can get a notification in real time whenever a new comment/thread is posted for that discussion.

**Comment by bmcutler** [comment]
Hi @ndixita,
Yes, we are calling them "categories" and they are on the phase of todo for the forum Issue #1677
And yes, a notification system is on the longer term horizon as well.  Some sort of alert or highlight or  when you're logged into Submitty.  And possibly also the ability to send email from the Submitty server for instructor announcements and more general notifications.
