### ISSUE TITLE
New Gradeable Model Integration

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2317]
Once #2107 gets finished (gradeable model classes), they will need to be integrated into the rest of the codebase.  The most significant parts are as follows (update as needed):
- [x] Add per-testcase results into `AutoGradedGradeable` (#2379)
- [x] Navigation View (#2407)
- [x] Create/Edit Gradeable (#2356)
- [x] Electronic Grader (#2970)
- [x] Simple Grader (#2406)
- [x] Submission page (first part: #2432)
- [x] Team Controller (#2985)
- [x] Reports Controller (#3174)
- [x] Late Days Calculation (#3043)
- [x] Gradeable Controller (#2986)
- [ ] Delete old model

There will be many other places that will need to be updated, but they shouldn't be as involved.
