### ISSUE TITLE
[Office Hours Queue] feature ideas / todo list

### ISSUE THREAD

**Issue by elihschiff** [Submitty/Submitty#4667]
### Short Term:
   * [ ] Color the help button green for students who have not been helped yet today
   * [ ]  Add message to student page letting them know that after they have been helped once today they will be marked as such
   * [ ]  Redo all status codes to be more clear (maybe a multi digit number where each power of 10 has its own role)
   * [ ]  Change the database to have both the person who starts helping and the person who finished helping stored
   * [ ]  Students should be able to click finish helping themselves in case the TA forgets
   * [ ] When the queue is closed students should still see their spot in the queue
   * [ ] When the queue is closed students not in the queue should see a message saying it is too late
   * [ ]  When the queue is closed and nobody is left in the queue put a message for everyone that says queue is closed
   * [ ]  Add a drop-down where students can add labels next to them in the queue. Let the mentors add or remove example labels. Also let students add a custom label to their name. 
 * [ ]  custom message that Instructor/mentors/ta can add that students can see

### Long Term:

 * [ ] Add a "eye" button to show the student's id (like how the forum does it)
 * [ ] Add a button to show a student photo before you help them
 * [ ]  Think of ways to encurage students to remove themselves from the queue if they solve their own issue
 * [ ]  make queue work for labs

**Comment by MasterOdin** [comment]
> * When the queue is closed students not in the queue should see a message saying it is too late
> * When the queue is closed and nobody is left in the queue put a message for everyone that says queue is closed

I'd vote to just combine these into a "Queue is closed". I'm not sure we need special messaging between these two cases as they're both in effect "Queue is closed" and no matter what you put, some students are going to complain / try and persist for extra time.
