### ISSUE TITLE
TODO revisions to Elapsed Time autograding

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#5303]
TODOs from PR #5286:

- [ ] only copy queue file, user assignment settings & access if this is "copy_access_files" is set
       in autograder/autograder/execution_environments/secure_execution_environment.py

- [ ] fix the format of the date time string 
   search in
    autograder/autograder/autograding_utils.py
   and 
    more_autograding_examples/notebook_time_limit/config/custom_validation_code/timelimit.py 

- [ ] store the access data in the course database instead of a file per student in the submissions folder
    NOTE: keep the global logging of access in /var/local/submitty/logs/access.
    -  [ ] add a table to the course database for gradeable page access
    -  [ ] each time a student accesses a gradeable page, add an entry
    -  [ ] each time a student submits a gradeable, write the user_assignment_access 
            file from the database contents.
        This is to help with performance on the system.  Frequently writing small
         not recently accessed files on a production VM.

- [ ] make time limit autograding a built in validation
    - [ ] display the first access on the page even if you haven't submitted yet.  
            and display a count down timer.
    - [ ] only display the duration on time limit test cases

- [ ] make test cases

- [ ] make the time duration override work for team (low priority, not sure it is necessary)
