### ISSUE TITLE
Move CI from Travis to Github actions

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#6212]
List of things needed to be done to move from TravisCI to GitHub actions:

Next steps:
- [x] move e2e tests to actions ( #6204 )
- [x] move git tests to actions (#7197) (needs debugging?)
- [x] debug pam auth on github actions ( #6249 )
- [x] fix and move integration tests to actions ( #6240 )
- [x] move code coverage ( #6204 )
- ~move slack notifier to actions~ (non-goal as we would like to avoid flooding slack with automated messages)
- [x] remove travis yml completely ( #6235 )
- [x] create weekly test for a full vagrant up against master ( #6462 ) 
- [x] proper PHP version handling for PHP unit tests, static analysis and lining ( #6204 )

**Comment by wusatosi** [comment]
I don't think `Cache pip` is working.
For example if you see the GitHub action triggered by the latest commit e33b67e4cc4892d00edd894257e13f3408ed8826 :
Log: https://github.com/Submitty/Submitty/runs/2433159805?check_suite_focus=true#step:8:20
The log says:
```
Received 22 of 22 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (22 B) <<< SEE HERE
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/9ef3919a-4e7e-4d6e-b822-21ad22725245/cache.tzst -P -C /home/runner/work/Submitty/Submitty
Cache restored successfully
Cache restored from key: Linux-py-pip-
```

**Comment by wusatosi** [comment]
On the subject of `create weekly test for a full vagrant up against master`.
Github action's Linux instances do not support nested virtualization, however, macOS instances do (weirdly). 
There's an action for setting up vagrant in GitHub action, it's [here](https://github.com/marketplace/actions/vagrant-virtualbox).

**Comment by wusatosi** [comment]
Slack notifier labeled as non-goal as automated flooding slack with automated message will hide other human message in slack due to a cap on the message count.

**Comment by MasterOdin** [comment]
To re-iterate some discussion from slack here, when we were using Travis, there was no way to control how you would individually be notified. If email was notified, then you'd always get an email, which some developers found annoying. The compromise was to post build messages to Slack to make it possible to track for those who wanted to do so (I have slack filters to pick up any messages of builds I kicked off for example). To help us minimize the amount of bot messages that were in our total message quota, I wrote https://github.com/Submitty/slack_bot_cleaner to prune them on a regular basis.

In moving to GH actions, it seems that it gives the fine grained control of notifications to people how they want it (no notifications, email, GH notifications, etc.) and so I think renders the slack notifier unnecessary at this time. Thanks @wusatosi for looking into this and sorry for any wasted effort on this as _why_ we had the slack channel for Travis was clearly not well documented anywhere.
