### ISSUE TITLE
Plagiarism Small Bugs Todo List

### ISSUE THREAD

**Issue by sbelsk** [Submitty/Submitty#6568]
**Describe the bug**
- [x] There is an off by one error in the front-end of the plagiarism results page where the last matching region/token of a type category (matches of type "match", "common", "provided") is not highlighted
![image](https://user-images.githubusercontent.com/71195502/121085997-9e5d0580-c7b0-11eb-9596-da7c9ac1ec1d.png)

- [x] We need to not make `matches.json` files for submissions that have no matches of type "match", even if they have match of type "provided" and/or "common"
- [ ] Fix/discuss percentages displayed for user 1 and user 2 on the side-by-side display
- [x] The "Last Run" and "Submissions" columns never display any data: ![image](https://user-images.githubusercontent.com/71195502/121201197-55559180-c842-11eb-8543-18f349778ebb.png)
- [x] The message displayed in this pop-up when clicking the "delete" button on a plagiarism run:
![image](https://user-images.githubusercontent.com/71195502/121201883-dca30500-c842-11eb-8c5b-2ce94f01d44f.png)
- [ ] The legend for the highlighted matches has no borders for the colors, so the color white for "unique matches" cannot be seen in light mode
![image](https://user-images.githubusercontent.com/71195502/121206495-82a43e80-c846-11eb-947a-b9807e20c217.png)

- [x] The new Plagiarism Detection Configuration page should not allow you to submit or create a new config with threshold = 1. Currently, if you do, the gradable completely disappears from the result summary page.

**Comment by sbelsk** [comment]
- [ ] The "Last Run" and "Submissions" columns never display any data
![image](https://user-images.githubusercontent.com/71195502/121201197-55559180-c842-11eb-8543-18f349778ebb.png)

**Comment by williamjallen** [comment]
@MasterOdin Not everything on this list has been completed.  Should this be reopened?

**Comment by MasterOdin** [comment]
Can you make an issue for the remaining tasks? Having these omnibus issues makes it annoying to deal with

**Comment by williamjallen** [comment]
Ok.  We just didn't want to create tens of small, trivial issues.  We'll separate the remaining tasks into new issues.

**Comment by MasterOdin** [comment]
As I've said previously, would be good to try not to open these sort of omnibus issues where each bug / task is discrete and will have its own individual PR for it. This makes it easier to book-keep things, as well as understand the link between issue and PR at a glance.
